---
- hosts: localhost
  tasks:
    - name: Creates keyrings folder
      become: yes
      file:
        path: /etc/apt/keyrings
        state: directory
    - name: Adds Docker GPG key
      become: yes
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    - name: Sets up repository
      become: yes
      shell: "echo 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable' | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null"
    - name: Install Docker
      become: yes
      apt:
        deb: https://desktop.docker.com/linux/main/amd64/docker-desktop-4.11.1-amd64.deb
        update-cache: true
    - name: Creates docker group
      become: yes
      group:
        name: docker
    - name: Adds user to docker group
      become: yes
      user:
        name: "{{ lookup('env', 'USER') }}"
        group: docker
