- hosts: localhost
  vars:
    wallpapers_folder: "{{ lookup('env', 'HOME') }}/Pictures/Wallpapers"
    wallpaper_path: "{{ wallpapers_folder }}/wallpaper.jpg"
  pre_tasks:
    - name: Update APT
      become: yes
      apt:
        force_apt_get: true
        update_cache: true
        state: present
  tasks:
    - include: tasks/core.yml
    - include: tasks/tweaks.yml
    - include: tasks/vivaldi.yml
    - include: tasks/discord.yml
    - include: tasks/git.yml
    - include: tasks/nvim.yml
    - include: tasks/zsh.yml
    - include: tasks/security.yml
    - include: tasks/work.yml
    - include: tasks/asdf.yml
    - include: tasks/dotfiles.yml
    - include: tasks/node.yml
