- hosts: localhost
  pre_tasks:
    - name: Update APT
      become: yes
      apt:
        force_apt_get: true
        update_cache: true
        state: present
  tasks:
    - include: tasks/core.yml
    - include: tasks/vivaldi.yml
    - include: tasks/discord.yml
    - include: tasks/git.yml
    - include: tasks/nvim.yml
    - include: tasks/zsh.yml
