- name: Git Clone ASDF
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf
    version: v0.10.0
- name: Check .zshrc exists
  stat:
    path: $HOME/.zshrc
  register: zshstats
- name: Append ASDF to .zshrc
  shell: echo ". $HOME/.asdf/asdf.sh" >> $HOME/.zshrc
  when: zshstats.stat.exists == True
