- name: Remove neovim folder
  file:
    path: "{{ lookup('env', 'HOME') }}/neovim"
    state: absent
  become: yes

- name: Clone Neovim
  git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
    version: release-0.7

- name: Build Neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo -j 20"

- name: Install Neovim
  become: yes
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && checkinstall"

- name: Remove neovim folder
  file:
    path: "{{ lookup('env', 'HOME') }}/neovim"
    state: absent
