- name: Remove Neovim
  file:
    path: ~/neovim
    state: absent

- name: Clone Neovim
  git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
    version: release-0.7

- name: Build Neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make -j 20"

- name: Install Neovim
  become: yes
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && checkinstall"
