- name: Remove Neovim
  file:
    path: ~/neovim
    state: absent

- name: Install Vim Plug
  shell: 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
                                                       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
- name: Clone Neovim
  git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
    version: release-0.7

- name: Build Neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make -j 20"

- name: Install Neovim
  become: yes
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && checkinstall"
